[2025-04-25T00:24:11.461+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-25T00:24:11.469+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_lab.check_latest_date manual__2025-04-25T00:24:04.653003+00:00 [queued]>
[2025-04-25T00:24:11.473+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_lab.check_latest_date manual__2025-04-25T00:24:04.653003+00:00 [queued]>
[2025-04-25T00:24:11.473+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-25T00:24:11.478+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): check_latest_date> on 2025-04-25 00:24:04.653003+00:00
[2025-04-25T00:24:11.482+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=330) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-25T00:24:11.483+0000] {standard_task_runner.py:72} INFO - Started process 332 to run task
[2025-04-25T00:24:11.483+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '***_lab', 'check_latest_date', 'manual__2025-04-25T00:24:04.653003+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpvg37fpnv']
[2025-04-25T00:24:11.486+0000] {standard_task_runner.py:105} INFO - Job 170: Subtask check_latest_date
[2025-04-25T00:24:11.511+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_lab.check_latest_date manual__2025-04-25T00:24:04.653003+00:00 [running]> on host 3b98ce16fd30
[2025-04-25T00:24:11.552+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_lab' AIRFLOW_CTX_TASK_ID='check_latest_date' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T00:24:04.653003+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-25T00:24:04.653003+00:00'
[2025-04-25T00:24:11.552+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-25T00:24:11.554+0000] {logging_mixin.py:190} INFO - Checking latest date in Snowflake table: TB_SYMPTOMS_GGSHEET
[2025-04-25T00:24:11.559+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-04-25T00:24:11.559+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.2, Python Version: 3.12.6, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-25T00:24:11.560+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-25T00:24:11.560+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-25T00:24:12.220+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-25T00:24:12.225+0000] {logging_mixin.py:190} INFO - Latest date in Snowflake table: 2021-01-31 19:01:00-08:00
[2025-04-25T00:24:12.226+0000] {connection.py:788} INFO - closed
[2025-04-25T00:24:12.301+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-04-25T00:24:12.487+0000] {python.py:240} INFO - Done. Returned value was: 2021-01-31 19:01:00-08:00
[2025-04-25T00:24:12.511+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-25T00:24:12.512+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_lab, task_id=check_latest_date, run_id=manual__2025-04-25T00:24:04.653003+00:00, execution_date=20250425T002404, start_date=20250425T002411, end_date=20250425T002412
[2025-04-25T00:24:12.560+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-25T00:24:12.578+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-25T00:24:12.580+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
